version: '3'

services:
  pkubigdata:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pku-2024bigdata:latest
    container_name: pkubigdata
    volumes:
      - ./auto_create_hive_table:/app/auto_create_hive_table
      - ./dw:/app/dw
      - ./logs:/app/logs
    environment:
      - ORACLE_HOME=/usr/lib/oracle/client
      - LD_LIBRARY_PATH=/usr/lib/oracle/client
      - TNS_ADMIN=/app/auto_create_hive_table/resources
    networks:
      - pkubigdata_network

networks:
  pkubigdata_network:
    driver: bridge 